[package]
name = "test-programs"
version = "0.1.0"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures-lite.workspace = true
serde_json.workspace = true
wstd.workspace = true
